### PR TITLE
fix some printing inconsistencies

### LINKED ISSUE #271: Diff printing when changing between branch and commit
```
pkg> add Literate

pkg> add Literate#master
```
Changing to a commit should presumably print something like `Literate v0.1.0+ #master ⇒  Literate v0.1.0+ #b57e6cc`, but we only get

```
pkg> add Literate#b57e6cc
  Updating git-repo `https://github.com/fredrikekre/Literate.jl.git`
  Updating registry at `~/.julia/registries/Uncurated`
  Updating git-repo `https://github.com/JuliaRegistries/Uncurated.git`
 Resolving package versions...
  Updating `~/.julia/environments/v0.7/Project.toml`
 [98b081ad] ~ Literate v0.1.0+ #b57e6cc
  Updating `~/.julia/environments/v0.7/Manifest.toml`
 [98b081ad] ~ Literate v0.1.0+ #b57e6cc
```
and same problem when adding back to master:
```
pkg> add Literate#master
  Updating git-repo `https://github.com/fredrikekre/Literate.jl.git`
  Updating registry at `~/.julia/registries/Uncurated`
  Updating git-repo `https://github.com/JuliaRegistries/Uncurated.git`
 Resolving package versions...
  Updating `~/.julia/environments/v0.7/Project.toml`
 [98b081ad] ~ Literate v0.1.0+ #master
  Updating `~/.julia/environments/v0.7/Manifest.toml`
 [98b081ad] ~ Literate v0.1.0+ #master
```

Also, when using `Revise` as the test package, nothing is printed at all:

```
pkg> add Revise#7350aff
  Updating git-repo `https://github.com/timholy/Revise.jl.git`
  Updating registry at `~/.julia/registries/Uncurated`
  Updating git-repo `https://github.com/JuliaRegistries/Uncurated.git`
 Resolving package versions...
  Updating `~/.julia/environments/v0.7/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v0.7/Manifest.toml`
 [no changes]

pkg> add Revise#master
  Updating git-repo `https://github.com/timholy/Revise.jl.git`
  Updating registry at `~/.julia/registries/Uncurated`
  Updating git-repo `https://github.com/JuliaRegistries/Uncurated.git`
 Resolving package versions...
  Updating `~/.julia/environments/v0.7/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v0.7/Manifest.toml`
 [no changes]
```

### PR DESCRIPTION
**Pull request by KristofferC**
```
(Pkg3) pkg> add Literate#b57e6cc
...
  Updating `Project.toml`
 [98b081ad] ~ Literate v0.1.0+ #master ⇒ v0.1.0+ #b57e6cc
  Updating `Manifest.toml`
 [98b081ad] ~ Literate v0.1.0+ #master ⇒ v0.1.0+ #b57e6cc

(Pkg3) pkg> add Revise#master
...
   Updating `Project.toml`
 [295af30f] ~ Revise v0.3.0+ #7350aff ⇒ v0.3.0+ #master
  Updating `Manifest.toml`
 [295af30f] ~ Revise v0.3.0+ #7350aff ⇒ v0.3.0+ #master
```

Fixes #271

### CODE REVIEW

File: src/Display.jl [hunk 1]
```diff
@@ -81,7 +81,7 @@ end
 function print_project_diff(ctx::Context, env₀::EnvCache, env₁::EnvCache)
     pm₀ = filter_manifest(in_project(env₀.project["deps"]), env₀.manifest)
     pm₁ = filter_manifest(in_project(env₁.project["deps"]), env₁.manifest)
-    diff = filter!(x->x.old != x.new, manifest_diff(ctx, pm₀, pm₁))
+     diff = filter!(x->x.old != x.new, manifest_diff(ctx, pm₀, pm₁))
```
Comment (fredrikekre) [inline src/Display.jl]: ?
